version: "3.9"

services:
  manage:
    image: taigaio/taiga-back
    environment:
      CELERY_ENABLED: "False"
    env_file: .env
    depends_on:
      - postgres
    entrypoint: "python manage.py"
    volumes:
      - ./static:/taiga-back/static
      - ./media:/taiga-back/media
    networks:
      - local